sonar.organization=ujjwal000167
sonar.projectKey=Ujjwal000167_university-jadeja

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=backend,frontend
